#!/bin/sh
### BEGIN INIT INFO
# Provides:     teamspeak
# Required-Start:   $network mysql
# Required-Stop:    $network mysql
# Default-Start:    2 3 4 5
# Default-Stop:     0 1 6
# Short-Description:    TeamSpeak 3 Server
### END INIT INFO

DESC="TeamSpeak 3 Server"
NAME="ts3server"
DIR="/usr/local/teamspeak"
DAEMON="${DIR}/${NAME}"
PIDFILE="/var/run/$NAME.pid"
USER="teamspeak"
OPTIONS="inifile=ts3server.ini"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

do_start () {
    start-stop-daemon --start --background --quiet --oknodo \
        --retry 5 \
    --make-pidfile \
        --chuid $USER \
        --chdir $DIR \
        --pidfile $PIDFILE \
        --exec $DAEMON \
        -- $OPTIONS
}

do_stop () {
    start-stop-daemon --stop --quiet --oknodo \
        --retry 5 \
    --remove-pidfile \
        --pidfile $PIDFILE \
        --exec $DAEMON
}

case "$1" in
    start)
        export LD_LIBRARY_PATH="${DIR}:${LD_LIBRARY_PATH}"
        log_daemon_msg "Starting ${DESC}" "${NAME}"
        do_start
        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping ${DESC}" "${NAME}"
        do_stop
        log_end_msg $?
        ;;
    restart)
        log_daemon_msg "Restarting ${DESC}" "${NAME}"
        do_stop
    sleep 1
        do_start
        log_end_msg $?
        ;;
    status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
    *)
        echo "Usage: ${0} {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
